[package]
name = "towa-js-port"
version = "0.1.0"
edition = "2021"
description = "A super strong and super slow encrypt-er"
repository = "https://github.com/haruki-nikaidou/towa-core"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
towa-core = "0.1.0"
wasm-bindgen = "0.2.89"
